### ISSUE TITLE
关于worker进程中，在业务中使用static变量的问题

### ISSUE THREAD

**Issue by bingcool** [kiss291323003/easyswoole#13]
在woker进程业务中可能会用到static的静态变量问题，如何避免多个客户端同时访问这些静态变量，可能出现混乱的问题

**Comment by kiss291323003** [comment]
由于进程隔离问题，在worker中的static变量实际上是在每个进程内独立存在的。而在阻塞模式下，不会存在这个问题。如果需要多进程共享，请使用里面提供的shareMemory或者是redis等其他工具

**Comment by bingcool** [comment]
阻塞模式下，比如比如一个类有一个静态变量默认值static name = null（或者其他），现在一个请求访问，设置了一个类的静态变量传入参数$name=bbbb,例如if(!self::$name) {self::$name = $name}，那么在这个请求访问过后，其实这个name的值已经是长驻内存等于bbbb了，那么当接着有另一个访问的这个类的时候,要设置$name=aaaa，比如,代码依然是判断if(!self::$name) {self::$name = $name}，那么可以发现，其实这段代码并不会执行了，因为这个self::$name并不是默认时的null了，所以在编程中很容易出错，这是一个需要解决的问题，最近一直在找一些方案

**Comment by kiss291323003** [comment]
额、、、、这个的话  你参考下easyswoole里面 http request 和Response实现单例的方法
