### ISSUE TITLE
需要加入自定义常量及一些自定义命名空间

### ISSUE THREAD

**Issue by hanwenbo** [kiss291323003/easyswoole#20]
Log、Temp、Core目录的常量自定义；
App\Controller 常量自定义；
现在开发者需要修改server的预加载才能解决，解决了还会有bug，为了从根本上解决，希望官方能及时留出接口

**Comment by kiss291323003** [comment]
好的

**Comment by hanwenbo** [comment]
你已经解决了 我前天已经更新了 感谢！！
