### ISSUE TITLE
异常处理、非致命错误的体验优化建议。

### ISSUE THREAD

**Issue by hanwenbo** [kiss291323003/easyswoole#25]
这块呢，通过我使用，我发现新用户调试很吃力，由于用了tp或其他框架，都有异常处理 大伙对异常处理的了解就少，es warning错误会显示在页面上，调试节奏慢，这时大家就卡壳了 需要去封装异常处理。
我觉得不如让非致命的、异常的默认不要在页面上显示，让大家先用起来，让其去快速流程的实现功更有乐趣和成就感。
随着社区的发展，轮子多了，大家在看个人爱好去装自己喜好的异常处理依赖。

以上仅代表个人观点，具体处理方式还需要群主根据大局来权衡。

**Comment by kiss291323003** [comment]
好的  已经处理，非常感谢建议  很有用
